version: "3.9"

services:
  huiscrawler:
    container_name: huiscrawler
    image: ghcr.io/adriaanvanrossum/huiscrawler:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATA_DIR: "/data"
      TZ: "${TZ}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
      GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PROMPT: "${PROMPT}"
      PORT: "${PORT:-3008}"
    ports:
      - "127.0.0.1:${PORT:-3008}:${PORT:-3008}"
    volumes:
      - /home/adriaan/huiscrawler:/data
